MODULE ANOVA_CONSTANTS 

  LOGICAL, PARAMETER :: ANOVA_MEASURE = .TRUE.  
  LOGICAL, PARAMETER :: ANOVA_VERBOSE = .TRUE. 
  REAL(KIND=8), PARAMETER :: SMALL_DELTA = 1.E-10 

  INTEGER, PARAMETER :: &  
       STDIN=5, &
       STDOUT=6 

    INTEGER, PARAMETER :: & 
         DTOT=1, &  
         DYXZT=2 ,&
         DYXZ=3, DYXT=4, DYZT=5, DXZT=6, & 
         DYX=7, DYZ=8, DYT=9, DXZ=10, DXT=11, DZT=12, &
         DY=13, DX=14, DZ=15, DT=16, &
         DLAST=16
  



END MODULE ANOVA_CONSTANTS
